version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DB_CLIENT=pg
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=bunq_user
      - DB_PASSWORD=secure_password
      - DB_NAME=bunq_tickets
      - JWT_SECRET=your-super-secure-jwt-secret-256-bits-minimum
      - SLACK_ENABLED=true
      - SLACK_WEBHOOK_URL=https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK
      - ALLOWED_ORIGINS=http://localhost:3000,https://your-frontend-domain.com
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=bunq_tickets
      - POSTGRES_USER=bunq_user
      - POSTGRES_PASSWORD=secure_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data:
